### ISSUE TITLE
Introspection Codepoint

### ISSUE THREAD

**Issue by A60AB5450353F40E** [bitjson/cashtokens#13]
The same codepoint can be defined across 3 contexts: input's unlocking script prefix, Script VM, output's locking script prefix.

We can use the same `0xef` for a Script VM opcode, and in another issue I had proposed to use in the input to declare a category's initialization state, and in the Script VM to access that state.

It got me thinking, could we contain the proposal to using up just 1 codepoint by making introspection opcodes pop 2 stack values, one for the index, other for the property being read. This would make the opcode more expensive but on the other hand we could avoid having to slice the capability off the categoryID opcode, and instead have a mode for obtaining it directly.

**Comment by A60AB5450353F40E** [comment]
Trying this out on the Group CHIP, gonna copy it verbatim here for info, it applies the same since my working v7 mirrors CT except for a few details. Went for 3 opcodes so it's consistent with one opcode per context approach of the Introspection CHIP.

### Group Annotation Introspection

We will extend [CHIP-2021-02: Native Introspection Opcodes](https://gitlab.com/GeneralProtocols/research/chips/-/blob/master/CHIP-2021-02-Add-Native-Introspection-Opcodes.md) with 3 **binary** opcodes, one for each context in which a group state may appear: `OP_INPUTPFXGROUP`, `OP_UTXOPFXGROUP`, and `OP_OUTPUTPFXGROUP`.
Each will pop two stack items as Script numbers: an input or output index, and the PreFiX field index.
If so referenced field exists then they will push its value to the stack, else push an empty stack element.

There are 5 values that can be returned for each context, leading to total 15 possible calls:

- `<0> <0> OP_INPUTPFXGROUP` returns first transaction input's `group genesis hash type`.
- `<0> <1> OP_INPUTPFXGROUP` returns first transaction input's `initial token type`.
- `<0> <2> OP_INPUTPFXGROUP` returns first transaction input's `initial fungible token amount`.
- `<0> <3> OP_INPUTPFXGROUP` returns first transaction input's `initial nft message length`.
- `<0> <4> OP_INPUTPFXGROUP` returns first transaction input's `initial nft message`.
- `<0> <0> OP_UTXOPFXGROUP` returns first transaction input UTXO's `group ID`.
- `<0> <1> OP_UTXOPFXGROUP` returns first transaction input UTXO's `token type`.
- `<0> <2> OP_UTXOPFXGROUP` returns first transaction input UTXO's `fungible token amount`.
- `<0> <3> OP_UTXOPFXGROUP` returns first transaction input UTXO's `nft message length`.
- `<0> <4> OP_UTXOPFXGROUP` returns first transaction input UTXO's `nft message`.
- `<0> <0> OP_OUTPUTPFXGROUP` returns first transaction output's `group ID`.
- `<0> <1> OP_OUTPUTPFXGROUP` returns first transaction output's `token type`.
- `<0> <2> OP_OUTPUTPFXGROUP` returns first transaction output's `fungible token amount`.
- `<0> <3> OP_OUTPUTPFXGROUP` returns first transaction output's `nft message length`.
- `<0> <4> OP_OUTPUTPFXGROUP` returns first transaction output's `nft message`.

Note that raw transaction format uses the "VarInt" number serialization to encode numbers in a more compact form which is incompatible with Script VM.
Introspection opcodes will be specified so that VarInts are always pushed to Script VM stack in their deserialized form, so that Script VM may directly use the returned value as a Script number instead of having to extract it from the encapsulation.

Specifying group annotation introspection as 3 binary opcodes is a compromise between contract byte-efficiency and using too many of the remaining and scarce Script VM code-points.
The `OP_INPUTPFXGROUP` will be specified at the same code-point `0xEE` as the `PFX_GROUP_GENESIS` and `PFX_GROUP`, completing the definition across all 3 contexts.

With the above, this proposal will use up a total of 3 code-points.

**Comment by A60AB5450353F40E** [comment]
even if we use implicit genesis as defined in CT2.0, we could still have genesis introspection opcodes - they'd return aggregate ft amount and nft capability of the 1st batch of outputs, see here: https://gitlab.com/0353F40E/group-tokenization/-/commit/3f5c77cc90769859cc1e2d37a5e21e1369cfcf96

**Comment by A60AB5450353F40E** [comment]
To add, I'm well aware of your rationale for having unary opcodes:

>Ah, you mean opcodes that accept two stack items... I may not be understanding your goal, but this is still my opinion on opcode complexity: https://gitlab.com/GeneralProtocols/research/chips/-/blob/master/CHIP-2021-02-Add-Native-Introspection-Opcodes.md#use-of-single-byte-opcodes

But those were for "main" TX fields, which we don't expect to increase greatly in number.

If we think of a PFX as one field, and id/amount/message as sub-fields, then why use up "main" codepoints for subfields. I fully  agree with your rationale about accompanying new fields with introspection opcodes, for this and future additions (can't remember where you wrote that).
We may add other PFX-es in the future, what if they will have multiple sub-fields? One opcode for each, or one opcode for the PFX and have the opcode encapsulate the PFX complexity?

We could just as well return the whole PFX as a composite and have the users slice it to extract the fields. Having the 2nd stack item tell the opcode what sub-field to return could save some bytes in certain scenarios but also waste some in others... so how to optimize, and optimize for what exactly?

My personal preference is towards readability and completeness, which is why I suggested exactly 3 opcodes, one for each context in which a token state may appear: prevout, output, and "virtual" input state (genesis), that would make the logic consistent with unary "main" opcodes, but still allow more granularity about what part of PFX to extract.

If we're moving towards expanding VM limits, will this byte-efficiency trade-off really be worth it?

**Comment by bitjson** [comment]
@A60AB5450353F40E and I talked about this separately, but just to document here: 

For consistency, the CashTokens introspection operations generally follow the same unary behavior as the [other inspection opcodes](https://gitlab.com/GeneralProtocols/research/chips/-/blob/master/CHIP-2021-02-Add-Native-Introspection-Opcodes.md) with the [(documented) exception of `OP_*TOKENCATEGORY`](https://github.com/bitjson/cashtokens#including-capabilities-in-token-category-inspection-operations) (where the deviation is very deliberate).

The value of keeping inspection operations cheap becomes even more clear when you review a non-trivial contract using them like https://github.com/bitjson/jedex – token inspection operations can easily take up 1/4 or 1/2 of some covenants, so efficiency here pays significant dividends.

(Closing this for now, but please let me know if I should re-open!)
