### ISSUE TITLE
Suggest renaming "VarInt" to CompactSize in the spec

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#16]
Since it's liable to cause confusion.  Note the bitcoin cash docs also use the term VarInt incorrectly.  VarInt != CompactSize. 

VarInt is used internally by the Core line of BCH nodes (Flowee, BCHN, BU) to save txos to the db and for other internal things.

CompactSize is what you meant in the spec.

Note that the Bitcoin Core docs about their txn serialization format etc make this distinction and call it a compactsize (and not a VarInt).

**Comment by bitjson** [comment]
Ah, thanks for the heads up @cculianu! I'll correct that in the next patch 👍

**Comment by cculianu** [comment]
Yeah maybe you can call it "compact integer" or something. I know everybody calls it VarInt sometimes but this can lead to confusion.. I appreciate it man!

BTW I am reading the spec now and will get to implementing either this or bitcoincashautist's spec (or maybe even both) at some point soon!

**Comment by bitjson** [comment]
Thanks again for the heads up here @cculianu! Fixed in `v2.1.0` 👍
