### ISSUE TITLE
FT Zero, NFT message NULL and EMPTY

### ISSUE THREAD

**Issue by A60AB5450353F40E** [bitjson/cashtokens#20]
Hey Jason, what's your view on these edge cases:

### FT Amount 0

If we allow 0-amount FTs that would be consistent with satoshi amounts, and would allow a way to "stamp" some data even  if the category is FT-only, like a 0-amount OP_RETURN. Only a FT could emit 0-amount UTXOs, a non-FT NFT could not.

### NFT message NULL and EMPTY

- No message = NULL (only ID + token_type encoded)
- Message of 0-length = EMPTY (only ID + token_type encoded)
- Message of >=1 length = the message (ID + token_type + nft_message field)

With your composite `ID||type` introspection opcode you could distinguish between NULL and EMPTY, and it could be usable as a free "bool" to be purposed by the contract. Toggling it would of course require mutable(edit) capability.

**Comment by cculianu** [comment]
Please no pure-FT amount 0.  I don't see much value in it and makes it annoying to deal with implementation-wise where anybody can color all of the coins they ever touched with their territorial pissing of amount 0.

**Comment by cculianu** [comment]
Also one can imagine allowing then "ANY" category to be pissed-on by amount=0 fungibles since why not? "nothing" is created from "nothing".

Please no.

**Comment by A60AB5450353F40E** [comment]
ok, so if I read it right updated spec is like this:

### Fungible Token Amount

- NULL not possible, because we always encode the amount field
- 0 allowed only with NFTs and means "no FT"
- >0 is regular

q: should 0 be allowed for FT-only outputs but limited to OP_RETURN? That would prevent 'territorial pissing' on UTXOs but would allow to tie some non-UTXO data to a categoryID

### NFT Commitment

- NULL not possible, or, if NULL then it means that also the NFT is NULL because there can't be an NFT with NULL commitment since NFT always encodes the commitment length
- EMPTY possible, means "no commitment", because every NFT encodes the length and len=0 means EMPTY
- soft limit of 40b using standard rules
- hard lmit of X? I suggest a new constant, but have it defined equal the stack item size =520.

**Comment by A60AB5450353F40E** [comment]
closing this... I'm happy with current spec where all 3 fields are always present on an utxo (nft capability, nft message length, ft amount)
