### ISSUE TITLE
Rationale: `OP_UTXOTOKENCOMMITMENT` and `OP_OUTPUTTOKENCOMMITMENT` push `0` for zero-length commitments

### ISSUE THREAD

**Issue by A60AB5450353F40E** [bitjson/cashtokens#25]
"If the UTXO includes a non-fungible token with a zero-byte commitment, push 0x00. If the UTXO does not include a non-fungible token, push a 0 (VM Number)."

If we encode a 1-byte commitment that encodes a `commitment[0]=0x00` it would result in the same 0x00 value being pushed to the stack.

Suggestion: push an empty stack item in both no-NFT and no-commitment cases, and the user should check the capability to distinguish no-NFT from no-commitment.

**Comment by bitjson** [comment]
Thanks for opening this issue @A60AB5450353F40E! That's definitely a rough edge right now.

Related: we probably don't want it to be possible to encode a `0x00` commitment in two ways, so if we keep the idea at all, it might at least be valuable to forbid the longer encoding (`0x0100`).

> Suggestion: push an empty stack item in both no-NFT and no-commitment cases, and the user should check the capability to distinguish no-NFT from no-commitment.

That's a good point, any contract that is just using zero-byte commitments could probably just use `OP_*TOKENCATEGORY` to confirm that the NFT exists. (They likely aren't going to issue fungible tokens for the same category that they're checking for zero-byte NFTs, but if needed, it's also pretty cheap to confirm that zero fungible tokens are attached to the output).

Some rationale: I'd originally selected `0x00` because it's short but not a valid number, so contracts can safely use both zero-byte NFTs and number commitments without extra validation. One downside of `0x00` is that it requires two bytes to push in contracts (`0x0100`). We could maybe use `0x81` to reduce that to a single byte (`OP_1NEGATE`) without making it confusable with commitments of positive numbers, but the that still runs the risk of being accepted by other validation looking for commitments with numbers.

But maybe I was trying too hard to make zero-byte NFTs efficient – tokens already cost at least 34 bytes to encode, adding a special case to encoding and inspection for zero-byte NFTs seems like a lot of complexity to save one byte in rare cases. (And like you said, most use cases will have other equally-efficient ways to look for a zero-byte NFT.)

---

Ya, seems like a good idea for zero-byte NFTs to push `0` for `OP_*TOKENCOMMITMENT`. I'll update that in the spec and work on describing it in the rationale, thanks!

(Will leave this issue open until a correction is merged.)

**Comment by A60AB5450353F40E** [comment]
No wait I think I misinterpreted zero-byte as zero-lenght, I think the spec is fine, just needs clarifications.

So when it comes to OP_*TOKENCOMMITMENT, lets go over all cases:
- no PFX, return EMPTY ("0x" in BitAuth) which is also numerical 0, or OP_0 right?
- commitment_length == 0, return EMPTY
- commitment_length == 1 and commitment == 0x00, return 0x00

**Comment by cculianu** [comment]
Just FYI: You know, there is no way to differentiate between NFT_Immutable with 0-byte commitment and NFT_Fungible.  You can't ask for the capability byte directly.  You can only ask for the categoryId with the capability byte appended.  And if you do, NFT_Fungible and NFT_Immutable both end up without a capability byte appended to the categoryId!

**Comment by A60AB5450353F40E** [comment]
Then let's please separate the FORMAT (has FT, has NFT, has NFT commitment) from the CAPABILITY (immutable, mutable, mint), it will all be much clearer. See #28 

And here I have a column specifying all 13 possibilities and what introspection should return for each: https://github.com/bitjson/cashtokens/issues/27#issuecomment-1179758616

**Comment by cculianu** [comment]
Ok, created #29 .

**Comment by cculianu** [comment]
@A60AB5450353F40E I'm on with that approach too as discussed in #28. .. but waiting on Jason to OK that one. In the meantime I have a suggestion in #29...

**Comment by A60AB5450353F40E** [comment]
>Dropping the 0x00 behavior also removes the discontinuity that can occur if non-padded numbers are used alone in a commitment: with the 0x00 approach, such contracts would need to include a special case for 0 too (and pushing most contracts to just pad those numbers, wasting 2-7 bytes per output).

Ah right... from point of view of Script API it is a discontinuity because if you're using commitment for non-padded numbers the 0x00 would be the only number requiring a `OP_BIN2NUM` to convert to 0 as ScriptNum. Other values would be directly usable as ScriptNum - as long as the user would respect the convention to not pad the numbers. So, returning 0x00 instead of 0 would "break" our user even if he used only non-padded numbers and he'd need a special treatment for the 0.

I saw it as discontinuity if you're using the commitment for some string that may have the value 0x00. If the opcode returns 0, then the string user needs to catch that and convert it to 0x00. What do you think will be more common?

>So after the discussion in this issue, I'm strongly leaning toward dropping OP_*TOKENCOMMITMENT's special handling for zero-length commitments. Returning 0x00 makes the protocol more complex and is unlikely to be used by well-optimized contract compilers (validating 0x00 is just as expensive as instead using a 1-byte, OP_1NEGATE-OP_16 commitment), while returning 0 for zero-length commitments will be a valuable optimization for many contracts (can save up to 7 bytes per output).

This answers it, and I'm now too leaning towards returning 0 (EMPTY stack item) and not "0x00".

In any case - it must be well documented and clear :)

**Comment by A60AB5450353F40E** [comment]
Ok @cculianu @bitjson  I think we can close it - it should continue to return 0, but we need to fix category opcode to return (ID+capability) in case of immutable instead of just the ID, see other issue.

Note re. encoding: the "no commitment" encoding should replace the "has commitment of 0x00" and "has 0-len commitment" which should both be disabled, since all 3 encodings would get mean the same thing from the point of view of Script API and we only need 1 encoding for the 0-commitment and the smallest one will be "no commitment" which can be a [34b encoding](https://github.com/bitjson/cashtokens/issues/28) (pfx+ID+0x43) where OP*CATEGORY would return ID+0x03 (immutable nft), and OP*COMMITMENT would return `0` as ScriptNum.

**Comment by A60AB5450353F40E** [comment]
And we could add a note to "design philosophy": it's like we start from Script API (introspection opcodes) and fully specify the logic we want there.. and then if there are multiple ways to encode the full API-returned state (OP\*CATEGORY, OP\*AMOUNT, OP\*COMMITMENT) then we should pick the more efficient one and disable others - which my format now does. Also, opcodes should allow for extension of number and commitment size and should fail if exceeding the current stack item or script number size.

With that in mind, here's a table.

OP\*CATEGORY | OP\*COMMITMENT | OP\*AMOUNT | Test Case
-- | -- | -- | --
EMPTY | EMPTY | EMPTY | No PFX
category_id | FAIL | FAIL | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb30fd0902cc...ccff0000000000000080`<sup>1</sup> Fail: ft_amount bigger than max script number and commitment longer thant max stack item size
category_id | FAIL | EMPTY | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb20fd0902cc...cc`<sup>1</sup> Fail: commitment longer than max stack item size
category_id | FAIL | ft_amount | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb30fd0902cc...cc01`<sup>1</sup> Fail: commitment longer than max stack item size
category_id | EMPTY | FAIL | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb10ff0000000000000080` Fail: ft_amount bigger than max script number
category_id | EMPTY | EMPTY | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb00`<sup>1</sup>
category_id | EMPTY | ft_amount | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1001`
category_id | commitment | FAIL | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb3001ccff0000000000000080`<sup>1</sup> Fail: ft_amount bigger than max script number
category_id | commitment | EMPTY | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb2001cc`<sup>1</sup>
category_id | commitment | ft_amount | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb3001cc01`<sup>1</sup>
category_id+nft_capability | FAIL | FAIL | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb73fd0902cc...ccff0000000000000080` Fail: ft_amount bigger than max script number and commitment longer thant max stack item size
category_id+nft_capability | FAIL | EMPTY | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb63fd0902cc...cc` Fail: commitment longer than max stack item size
category_id+nft_capability | FAIL | ft_amount | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb73fd0902cc...cc01` Fail: commitment longer than max stack item size
category_id+nft_capability | EMPTY | FAIL | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb53ff0000000000000080` Fail: ft_amount bigger than max script number
category_id+nft_capability | EMPTY | EMPTY | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb43`
category_id+nft_capability | EMPTY | ft_amount | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb5301`
category_id+nft_capability | commitment | FAIL | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb7301ccff0000000000000080` Fail: ft_amount bigger than max script number
category_id+nft_capability | commitment | EMPTY | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb6301cc`
category_id+nft_capability | commitment | ft_amount | `d0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb7301cc01`

Notes:

- OP\*CATEGORY does not have a fail case
- <sup>1</sup>Encodeable but disabled

**Comment by cculianu** [comment]
I don't clearly know what was concluded here because too much wall of text.  Just to be clear -- are we changing anything or are we not?  Note that in my implementation I went ahead already can changed it so that 0-length commitments are `{}` (the empty vector or VM number 0).  Do I change it back now to what was originally specified?

I don't understand or agree with the rationale but you guys are the ones that are designing this system for your contract needs so just tell me what you concluded.  @bitjson @A60AB5450353F40E

**Comment by bitjson** [comment]
Leaving this open until the spec is updated. `OP_UTXOTOKENCOMMITMENT` and `OP_OUTPUTTOKENCOMMITMENT` will push a `0` where they previously pushed `0x00`.

E.g. description for `OP_OUTPUTTOKENCOMMITMENT`:

`Pop the top item from the stack as an output index (VM Number). Push the token commitment of the output at that index to the stack. If the output does not include a non-fungible token, or if it includes a non-fungible token with a zero-length commitment, push a 0 (VM Number). If the token commitment is longer than the stack item length limit, fail evaluation.`

**Comment by bitjson** [comment]
(Ah, @cculianu see above for the impact of this issue ^)

**Comment by cculianu** [comment]
Ok, thanks.  That's what I already implemented.

**Comment by A60AB5450353F40E** [comment]
Yup, push `{}` for 0-length commitment

**Comment by bitjson** [comment]
The spec has been updated in https://github.com/bitjson/cashtokens/commit/6b5700f251f55b12b1b00af10d636f01c9f1de8e, leaving this issue open until rationale is clarified.
