### ISSUE TITLE
Single-prefix+bitfield token encoding

### ISSUE THREAD

**Issue by A60AB5450353F40E** [bitjson/cashtokens#28]
Proposed specification for the format, implements everything talked about in https://github.com/bitjson/cashtokens/issues/27 https://github.com/bitjson/cashtokens/issues/25 https://github.com/bitjson/cashtokens/issues/24 https://github.com/bitjson/cashtokens/issues/23

Because `nft_commitment` and `ft_amount` will be optional, then we get a more compact encoding for 0. So `ft_amount==0` will be disallowed because 0-value FT will be encoded by absence of HAS_FT_AMOUNT format flag so parsers can know to skip the `ft_amount`. Similarly, `nft_commitment_length==0` is disallowed because zero-byte commitment will be encoded by absence of HAS_NFT_COMMITMENT format flag so parsers can skip both `nft_commitment_length` and `nft_commitment`.

### S1 Transaction Format Changes

**Definitions**

We define transaction output prefix byte that will indicate presence of optional **category output annotation**:

- `OUTPUT_PREFIX_BYTE_CATEGORY = 0xd0`.

We define the maximum length for NFT messages:

- `MAX_SERIALIZED_NFT_COMMITMENT_LENGTH = 40`.

#### S1.1 Transaction Outputs

If `OUTPUT_PREFIX_BYTE_CATEGORY` byte is encoded at index 0 of a transaction outputs's locking script serialization then it will mark the start of a data structure that will encode the output category annotation.
The whole annotation, including the prefix byte, will be removed from the locking script before handing it to Script VM:

*`<satoshi value><locking script length>`* **`[OUTPUT_PREFIX_BYTE_CATEGORY <category data>]`** *`<real locking script>`*.

Category output annotation is defined as:

`OUTPUT_PREFIX_BYTE_CATEGORY <category_id> <token_format | nft_capability> [<nft_commitment_length><nft_commitment>] [ft_amount]`

where:

- `category_id` - a 32-byte value
- `token_format | nft_capability` - a 1-byte value containing 2 fields where they are deserialized as:
  - `token_format = serialized_byte & 0xf0` and
  - `nft_capability = serialized_byte & 0x0f`
- `nft_commitment_length` - a compact-size uint value that may encode a 1, 2, 4, or 8 byte uint, skip if `token_format & HAS_NFT_COMMITMENT == 0`
- `nft_commitment` - byte array of `nft_message_length` bytes, skip if `(token_format & HAS_NFT_COMMITMENT == 0) || (nft_commitment_length == 0)`
- `ft_amount` - a compact-size uint value that may encode a 1, 2, 4, or 8 byte uint, skip if `token_format & HAS_FT_AMOUNT == 0`

Bit flags that indicate presence of optional fields are defined as:

- HAS_NFT = 0x40,
- HAS_NFT_COMMITMENT = 0x20,
- HAS_FT_AMOUNT = 0x10.

Not all combinations will be allowed.

If `token_format == 0x00` then the transaction shall fail immediately. (REQ-1.1.1.)

If `(token_format & HAS_NFT == 0) && (token_format & HAS_NFT_COMMITMENT != 0)` then the transaction shall fail immediately. (REQ-1.1.2.)

These two requirements leave us with 5 allowed values for `token_format`, listed in table below.

`token_format` | bit7 | bit6 | bit5 | bit4 | bit3 | bit2 | bit1 | bit0 | Note
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
0x10 (16) | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | FT
0x40 (64) | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | NFT
0x50 (80) | 0 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | BOTH
0x60 (96) | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | NFT+commitment
0x70 (112) | 0 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | BOTH+commitment

If `token_format & HAS_NFT == 0` then `nft_capability` MUST be 0. (REQ-1.1.3.)

If `token_format & HAS_NFT > 0` then `nft_capability` MUST be one of allowed values:

- NFT_IMMUTABLE = 0x00,
- NFT_MUTABLE = 0x01,
- NFT_MINT = 0x02.

(REQ-1.1.4.)

When combined into the serialized byte, there will be 13 allowed states for the byte, as listed in table below.

`token_format` \| `nft_capability` | bit7 | bit6 | bit5 | bit4 | bit3 | bit2 | bit1 | bit0 | Note
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
0x10 (16) | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | FT
0x40 (64) | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | Immutable NFT
0x41 (65) | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 1 | Mutable NFT
0x42 (66) | 0 | 1 | 0 | 0 | 0 | 0 | 1 | 0 | Mint NFT
0x50 (80) | 0 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | FT + Immutable NFT
0x51 (81) | 0 | 1 | 0 | 1 | 0 | 0 | 0 | 1 | FT + Mutable NFT
0x52 (82) | 0 | 1 | 0 | 1 | 0 | 0 | 1 | 0 | FT + Mint NFT
0x60 (96) | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | Immutable NFT + commitment
0x61 (97) | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 1 | Mutable NFT + commitment
0x62 (98) | 0 | 1 | 1 | 0 | 0 | 0 | 1 | 0 | Mint NFT + commitment
0x70 (112) | 0 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | FT + Immutable NFT + commitment
0x71 (113) | 0 | 1 | 1 | 1 | 0 | 0 | 0 | 1 | FT + Mutable NFT + commitment
0x72 (114) | 0 | 1 | 1 | 1 | 0 | 0 | 1 | 0 | FT + Mint NFT + commitment

When encoded, value of `ft_amount` must obey these limits: minimum value of `1` and maximum value of `9223372036854775807` (`0xffffffffffffff7f`). (REQ-1.1.5.)

When encoded, value of `nft_commitment_length` must obey these limits: minimum value of `1` and maximum value of `MAX_SERIALIZED_NFT_COMMITMENT_LENGTH`. (REQ-1.1.6)

The annotation SHALL NOT count against length limits placed on `locking script`. (REQ-1.1.7)

**Comment by A60AB5450353F40E** [comment]
Afterthought: instead of failing the TX, we could define the NULL PFX (both format=0x00, nft_type=0x00, ft/commitment not encoded) an "unspendable" mark same like OP_RETURN, but it would write the ID and be accessible to scripts running on inputs in the same TX. If a contract set on immutable NFT wanted to verify a burn, it could just introspect the output's ID and check that the last byte is 0x00.

**Comment by A60AB5450353F40E** [comment]
@bitjson added a few cases that were missing like not enough length to encode a FT amount, I think there's a few more to add.

**Comment by bitjson** [comment]
To give us a head start on the rationale section if we go this direction: could you provide more detailed rationale for the changes here? How does your proposal differ from the current behavior, what use case(s) are improved, what are the savings?

**Comment by A60AB5450353F40E** [comment]
>To give us a head start on the rationale section if we go this direction: could you provide more detailed rationale for the changes here? How does your proposal differ from the current behavior, what use case(s) are improved, what are the savings?

Savings are:
- 0-value FT uses only 33b VS 35b in v2.1 spec (your multi-pfx approach would use 32b, though)
- 0-length commitment + 0-value FT uses only 33b (your multi-pfx approach could at best be the same 33b - and it would take either 5 PFX-es, or 3 PFXes + bit flag like here in the capability byte)
- Generally, it is minimal possible encoding except for the case of FT-only outputs where multi-pfx approach could shave 1 more byte
- Script use, capability uses numbers `<16`.
- I will edit this in now, to use HAS_NFT with nft_capability=0x00 for immutable, script use: encoding consistent with desired `immutable` Script API behavior (pure ID returned)

Other benefits:

- Clarity. Bitwise ops and bit flags are really the most natural way to encode a bool state in a compact way (optional field is or is not there - all you need is 1 bit for the info)
- Clarity. When we split format and capability encoding, you have a place which tells the parser what encoding follows (`token_format` flags are the first thing a parser will see), and you have a place which encodes one of the features (`nft_capability`). Think of them as 2x 1-byte fields packed into 1-byte.
- Clarity. When the byte is divided at half, you can "parse" it with your eyes: left letter is the format (1-ft, 4-nft, 5-both, 6-nft+commitment, 7-both+commitment), right letter is the capability (3-immutable, 7-mutable, F-mint).
- Extensibility. Because of how it's specified, if we ever needed more bits for `nft_capability`, the format could use a bit flag to indicate "capability lives in the next byte and is not packed with me" so we could encode capabilities `>0x0F`. Note: The multi-pfx approach would have 7 or 8 bits available for the capability (with 3 pfxes you'd need 1 bit to encode 0-commitment, with 5 pfxes you'd have full 8 bits for the capability)

Re. the multi-pfx... I suggest to save those for versioning.

**Comment by bitjson** [comment]
To clarify, I'm not asking you to convince me here/conversationally. 

**What is a concise, persuasive description that we could copy into the CHIP to convince all future readers?** How should we replace the [`Shared Codepoint for All Tokens`](https://github.com/bitjson/cashtokens#shared-codepoint-for-all-tokens) section?

No rush – I'm also trying to make up my mind and write a rationale too, and I still need to experiment with more options before I'll have a solid opinion.

**Comment by cculianu** [comment]
Not sure on the exact works, @bitjson  -- but to me the prefix byte is NOT part of the token payload.  It is a marker that the serialization layer of bitcoin looks at to know that it needs to take an alternate path to deserialize this token data that follows.  If it doesn't see that marker it does the legacy think and takes all the bytes and puts them in `scriptPubKey` 

As such, this is a "serialization hack" that we are doing.  It's best to contain your hacks into 1 byte as a marker.  Makes everything saner.

Again.. the serialization marker for the PREFIX_BYTE is *not part* of the token data payload, conceptually.  It's really a market for a **different layer** to denote what follows should be interpreted as **token data** using the token data deserialization rules.

I would argue it that way, if it were me.

**Comment by imaginaryusername** [comment]
"Prefix_byte marks the beginning of a different deserialization scheme which all the tokens share - distinct from other existing deserialization schemes - and it is cleaner implementation wise to separate the deserialization-scheme flag from the capabilities flag"

Does that make sense as a rationale?

**Comment by cculianu** [comment]
> "Prefix_byte marks the beginning of a different deserialization scheme which all the tokens share - distinct from other existing deserialization schemes - and it is cleaner implementation wise to separate the deserialization-scheme flag from the capabilities flag"

Perfect in my mind! ❤️

**Comment by A60AB5450353F40E** [comment]
>What is a concise, persuasive description that we could copy into the CHIP to convince all future readers?

Got it, let's try.

### Shared Codepoint for All Tokens

Though fungible and non-fungible tokens are entirely independent primitives, this specification defines the same PREFIX_TOKEN codepoint for encoding both token types.

While specifying separate "TOKEN_FUNGIBLE" and "TOKEN_NONFUNGIBLE" codepoints could save one byte for outputs that encode only fungible tokens, such separation would introduce significant overhead for covenants that operate on tokens of both types (within a single category): holding one token type would prevent covenants from holding the other type in the same output (assuming [outputs must have only one prefix](https://github.com/bitjson/cashtokens#one-prefix-codepoint-per-output)). While [depository covenants](https://github.com/bitjson/cashtokens#depository-child-covenants) can always be used to hold other categories of tokens, this option would still force many developers to use multi-output, "sidecar" covenant designs, even for relatively simple applications. Instead of "TOKEN_NONFUNGIBLE", a "TOKEN_DUAL" could be used to add support for these covenant cases. It could encode both NFT and NFT+FT cases, but specifying multiple token encodings would add implementation cost, for software like wallets, backends, indexers, block explorers.

It is conceptually clearer to treat the codepoint byte as a single switch that activates token validation code which will encapsulate processing the payload and enforcing consensus rules for it. In other words, the PREFIX_TOKEN marks the beginning of a different deserialization scheme which all the tokens share - distinct from other existing deserialization schemes - and it is cleaner implementation wise to separate the deserialization-scheme flag from the capabilities flag and the payload it encodes.

**Comment by bitjson** [comment]
Thanks all, I copied those points into https://github.com/bitjson/cashtokens/issues/27.

@A60AB5450353F40E: if you still think this is a better approach for encoding, would you mind making a PR?

**Comment by A60AB5450353F40E** [comment]
Will do!
