### ISSUE TITLE
Future Upgradeability

### ISSUE THREAD

**Issue by A60AB5450353F40E** [bitjson/cashtokens#31]
>E.g. even if we had a simple OP_OUTPUT_TOKEN_CAPABILITY that accepted an index and returned one of these above numbers (0, 3, 7, 15), while many contracts would be written to validate results by direct comparison ( OP_OUTPUT_TOKEN_CAPABILITY <3> OP_EQUAL), almost all byte-efficient contracts with multiple codepaths (based on capability) would be broken unpredictably: a contract might perform some validation for <=3, some for 7, and an OP_ELSE branch for the 15. If an upgrade slips a new 14 result into the set of possible results, it breaks the API used by that contract and produces a serious vulnerability.

This problem is not giving me rest. I first thought, well, if we make it so that new values are properly ordered, like if 14 is more restrictive than 7 and less restrictive than 15 then it should be no problem right? After all - it would not enable users to do new things. Well...

There's another class of problems: it could break public covenants. Imagine that anyone can access some covenant placed on immutable NFT (0x03) and then we enable making the Script field immutable too (0x01). What if the  public covenant relies on updating the contract's locking script with each tick, and requires "capability > 0" and then we enable 0x01 someone comes and slips in the 0x01 and breaks the contract by essentially terminating it because it would not be allowed to change its own locking script anymore.

As you suggested, solution would be to define a new codepoint for the new behavior, so existing categories would continue to operate under rules that were in force when they were created. Interaction between old/new could also be troublesome if same introspection opcodes would be used for both, so what could we do?

How about defining the OP\*CATEGORY to also return the PFX byte, the returned stack item would then be: PFX+ID+[nft_capability].

Also, imagine if in the future we define some scheme for fractional sats, like another PFX but without the ID, then we could probably use the same Script API (introspection opcodes) to interact with both CashTokens2.0 and some FracSats upgrade, the OP\*CATEGORY would return 1-byte value for FracSats.

Actually, because CashTokens are first - they don't need to return the PFX+ID, plain ID is enough, but some later upgrade would have to somehow expose to the Script API that it's not the same thing as CashTokens2.0, or it would need to define new introspection opcodes...

just some thoughts about strategy to upgrade

**Comment by bitjson** [comment]
For others finding this issue, I've written a lot about this problem – the quote in @A60AB5450353F40E's post above is from [Token encoding can't be directly upgraded](https://github.com/bitjson/cashtokens/issues/24#issuecomment-1179224180).

TLDR (from that link):

> I think what all this really means: we get one shot. We should try our best to get it perfect the first time. If future proposals realize we missed something important enough to be worth the effort of an upgrade, they'll have to contend with exposing the new functionality in a way that does not break contracts (and if desired, also doesn't break transaction parsers, i.e. new output prefixes).

**Comment by bitjson** [comment]
@A60AB5450353F40E I'm going to close this for now, but please re-open if something in the CHIP should change.
