### ISSUE TITLE
naming of OP_UTXO* is confusing.

### ISSUE THREAD

**Issue by zander** [bitjson/cashtokens#35]
The opcodes that start with "OP_UTXOTOKEN" caused me to get really confused for a while. There instantly was a thought towards the utxo-set, but that doesn't make sense. That is global info. Even "local" info makes it hard to figure out what an indexed utxo is..

Reading further I think what you named the utxo here is essentially the 'prev-out'. The previous-transaction's output.

Maybe to make it more understandable to most people a rename towards something like this makes sense?

`OP_PREVOUT_TOKENCATEGORY` and `OP_OUTPUT_TOKENCATEGORY` ? (repeat pattern for all opcodes described in this chip)

Its about readability and consistency, the numbers won't change.

**Comment by A60AB5450353F40E** [comment]
I think the ship has sailed with [Introspection CHIP](https://gitlab.com/GeneralProtocols/research/chips/-/blob/master/CHIP-2021-02-Add-Native-Introspection-Opcodes.md#unary-operations) which defined opcodes that read prevout's data (satoshi amount, locking bytecode) as `OP_UTXO*`. There's a distinction from prevout's reference (txid/vout index) which is referred to as `OP_OUTPOINT*`. Input's data is only the unlocking bytecode and sequence number, using `OP_INPUT*`.

**Comment by zander** [comment]
nah, the intospection chip hasn't made it into the BCH specification. I know its activated, but is its name defined when its not actually been listed in the any full nodes' spec yet?

The spec;  
https://documentation.cash/protocol/blockchain/script

The usage of 'utxo' in this context is really, well, taking it out of context. I don't really understand the logic behind it. The transaction is in actual fact spending it. A validator of a block (where the transaction is included in) would be using the utxo opcode to in actual fact fetch a spent transaction output.

This is the kind of naming that will be used for the next various decades and renaming it has no effect on running full nodes (or wallets), so please do consider putting a bit more time into that.
