### ISSUE TITLE
SIGHASH_UTXOS spec incomplete.

### ISSUE THREAD

**Issue by zander** [bitjson/cashtokens#37]
The text states;

> hashUtxos is inserted in the signing serialization algorithm immediately following hashPrevouts. hashUtxos is a 32-byte double SHA256 of the serialization of all UTXOs spent by the transaction's inputs (concatenated in input order).

Specifically the part "serialization of all UTXOs" is a problem, as that is not technically a field in Bitcoin full node software. I expect actual fields there (probably a subset of the input: https://flowee.org/docs/spec/blockchain/transaction/#transaction-input)

**Comment by A60AB5450353F40E** [comment]
UTXO = prevout. Serialization of input's prevouts so you'd want https://flowee.org/docs/spec/blockchain/transaction/#transaction-output fields
