### ISSUE TITLE
Clarify what is invalid as consensus vs what is unparseable (serialization level invalid)

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#44]
For example, from the spec right now:

> A token prefix encoding no tokens (both has_nft and amount are 0x00) is invalid.

Is this parseable but invalid consensus-wise? Or is this a lower-level parse failure (which leads to the byte blob assigned all to `scriptPubKey`)?  This distinction is now important since @bitjson plans on implementing #41 in the spec.

There are other such examples in the spec where it's unclear if parse failure or if token consensus failure.

**Comment by bitjson** [comment]
Thanks for opening this issue @cculianu! 

Fixed by #43. (Just referencing for GitHub.)

**Comment by bitjson** [comment]
I think this is done now, but please let me know if there are places that are still unclear!

**Comment by cculianu** [comment]
Well, assuming all the "invalid" test vectors are all for parse errors -- perhaps it is done.  I'll let you know if it's missing anything.

FWIW now that we don't overload the prefix-byte and since we completely disallow prefix-byte-containing outputs that are out-of-consensus AND don't parse, the delineation is not as important now... whereas before it was.
