### ISSUE TITLE
Specify that CompactSize must be "canonically encoded" and add test vectors that test this

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#45]
Non canonically encoded CompactSize should be rejected as parse failure.

What is a canonically encoded CompactSize?  Let's say you want to encode `40` (`0x28`). You have 4 options about how to encode it, but only one of them is canonical (it must be the minimally encoded representation, basically):

- `0x28` <-- canonical
- `0xfd2800` <-- not canonical (wastes space)
- `0xfe28000000` <-- again, non-canonical (wastes space)
- `0xff2800000000000000` <-- ditto

**Comment by bitjson** [comment]
💯 agreed, thanks for noticing! I'll correct that in the spec and add those test vectors. 👍

**Comment by bitjson** [comment]
Done 🚀

**Comment by cculianu** [comment]
Yeah I noticed it's in the test vectors now. Thanks.
