### ISSUE TITLE
Specify BIP69 sort order for txouts containing tokens

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#51]
Summary
---

BIP69 sorts outputs in a txn lexicographically by:

- `amount`
- `scriptPubKey`

A specification of how to sort the new `txouts` with tokens in them may be warranted.

Suggestion
---

Since token data conceptually doesn't live inside `scriptPubKey` (except for serialization but NOT on the application layer), it is onerous and a performance hit for implementations e.g. BCHN to re-serialize the token data just for bip69 txn sorting.

BIP69's philosophy is to sort by "cheapest to compare first".  As such this is how I am currently sorting token outputs in BCHN:

- `amount`
- `scriptPubKey`
- `tokenData`

Where `tokenData` sorts as follows:

```c++
    return std::tie(amount, capability, commitment, id) < std::tie(o.amount, o.capability, o.commitment, o.id);
````

Additionally, if all things are equal, `txouts` with **no token data** should sort **before** `txouts` **with token data**.

I politely suggest that maybe you should specify the above as the BIP69 sort order for Cash Token `txouts`.

**Comment by bitjson** [comment]
Thanks for the issue! I agree it makes sense to include a token extension for BIP69 in this CHIP. Would you be willing to send a PR?

**Comment by cculianu** [comment]
Sure!  I'll do so this weekend or during the week next week!

**Comment by cculianu** [comment]
I haven't had time to do this -- can you handle this? Or?

**Comment by bitjson** [comment]
@cculianu ya, I should be able to look at this soon 👍

**Comment by bitjson** [comment]
@cculianu are there any test vectors for this in BCHN yet?

**Comment by cculianu** [comment]
Yes but it's a unit test on the C++ side: https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/blob/58878d110f94ed5fc938365d83437e7e1f5122be/src/test/bip69_tests.cpp

**Comment by A60AB5450353F40E** [comment]
One note re. this: if bip69 is enabled by default then users will need a way to disable it when they want, for those smart contract TXes where having things in the right input/output slot matters. I know I've been annoyed by EC auto-sorting a TX imported from raw.
