### ISSUE TITLE
Please change CashAddr TOKEN types back to what was originally specified (0x2, 0x3).

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#52]
I already implemented this as types (2) and type (3).  You just randomly changed it here without any discussion, rationale, and/or warning.  It just creates extra work. 

https://github.com/bitjson/cashtokens/commit/5f24bb640b54d6900ba8c4bb99d2eb7ceae6eba9#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15R424

Please revert the types to `0x2` and `0x3` as before.  Thank you.

**Comment by cculianu** [comment]
See reasoning here for why original was better anyway: https://github.com/bitjson/cashtokens/issues/32#issuecomment-1200479800

Also, I already implemented it the original way.   I am putting my foot down on this one.  This is a test as to whether or not you are going to be a dictator or a cool guy, so would appreciate your not being a dictator. k Thanks.

**Comment by bitjson** [comment]
Responded here: https://github.com/bitjson/cashtokens/issues/32#issuecomment-1201762815, fixed in https://github.com/bitjson/cashtokens/commit/a751bb1131c0374459f3ccb7eee03be946515510 👍
