### ISSUE TITLE
Clarify `category` endianness test vectors in `token-prefix-valid.json`

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#53]
In the "valid" json test vectors there are broken tests. Specifically the second and third test have a typo in the expected category id (does not match the serialized token data).

**Comment by bitjson** [comment]
Those are there to ensure all implementations have deliberately checked how they handle endianness:

```json
  {
    "prefix": "ef21430000000000000000000000000000000000000000000000000000000034121001",
    "data": {
      "amount": "1",
      "category": "1234000000000000000000000000000000000000000000000000000000004321"
    }
  },
  {
    "prefix": "ef21436587090000000000000000000000000000000000000000000090785634121001",
    "data": {
      "amount": "1",
      "category": "1234567890000000000000000000000000000000000000000000000987654321"
    }
  },
```

So the test vectors use the same order as block explorers, where the block explorer will want the `category` to match the order it uses for transaction IDs. It seems a little safer to write test vectors this way so that each implementation has to at least consider the order – less likely to have endianness issues fly under the radar.

In what order does BCHN hold outpoint transaction hashes? Do you have to reverse the order to encode it for P2P messages? The intention is that we treat category ID exactly the same to keep things as simple as possible.

**Comment by bitjson** [comment]
It wasn't explicitly described in the spec before, but now it clarifies:

> [...] a 32-byte Token Category ID is required, encoded in `OP_HASH256` byte order<sup>1</sup>.
> [...]
> 1. This is the byte order produced/required by all BCH VM operations which employ SHA-256 (including `OP_SHA256` and `OP_HASH256`), the byte order used for outpoint transaction hashes in the P2P transaction format, and the byte order produced by most SHA-256 libraries. For reference, the genesis block header in this byte order is little-endian – `6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000` – and can be produced by this script: `<0x0100000000000000000000000000000000000000000000000000000000000000000000003ba3edfd7a7b12b27ac72c3e67768f617fc81bc3888a51323a9fb8aa4b1e5e4a29ab5f49ffff001d1dac2b7c> OP_HASH256`. (Note, this is the opposite byte order as is commonly used in user interfaces like block explorers.)

([Description taken directly from the introspection CHIP](https://gitlab.com/GeneralProtocols/research/chips/-/blob/master/CHIP-2021-02-Add-Native-Introspection-Opcodes.md#unary-operations).)

**Comment by cculianu** [comment]
Oh! Good catch.  Indeed when reading in the JSON I was treating it as little endian byte order rather than the (customary) big endian for string hex representation.

---

To answer your question: BCHN uses little endian order for hashes internally in memory. However, yes, when representing them as hex strings they do indeed get reversed as big endian.

Basically:

1. Order used internally (and in the serialization format) -- should be in **little endian byte order**. 
2. Indeed the string hex representation should be in big endian ordering (as is custom for hashes). I  made a mistake in the test case when reading in the JSON hex...

Indeed after treading the hex hashes as big endian it works now.

You may want to make all the test vectors actually be asymmetric endian-wise like these two are -- such that any regressions here are caught.
