### ISSUE TITLE
SIGHASH_UTXOS weakens the utility of double-spend proofs

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#54]
The addition of `SIGHASH_UTXOS` would break double-spend proofs for inputs signed with this sighash type. I say "break" in that DSPs as currently specified and implemented cannot capture all the information needed to prove a double-spend, if one of the conflicting inputs was spent using the proposed `SIGHASH_UTXOS`.  

This is because the proofs don't encapsulate all of the UTXOs used in the conflicting txn.  In fact, a node may even lack those UTXOs altogether.  All the proof really encapsulates is information about the spent UTXO that conflicts, not all of the UTXOs in a conflicting txn.  This was ok previous to the addition of   `SIGHASH_UTXOS` since before signing never involved examining all of the other coins in a txn.

The addition of `SIGHASH_UTXOS` to BCH would thus drastically weaken the utility of DSPs unless the DSP specification were also expanded somehow.  But even if the specification were expanded, it's not clear to me that such a proof would be possible since nodes may lack the UTXOs that a conflicting txn is referring to, thus making the proofs potentially impossible to both construct and verify.

Thus, an attacker can double-spend using the proposed `SIGHASH_UTXOS` and nobody would ever get an alert that such a txn were double-spent, thus weakening the utility of Double-Spend proofs.

**Comment by imaginaryusername** [comment]
`SIGHASH_UTXOS` should just be additionally specified to be incompatible with dsproof, just like `ANYONECANPAY` . People who care about its niche security context likely don't overlap much with people who need dsproof's fast retail capability.

**Comment by cculianu** [comment]
I didn't realize `SIGHASH_ANYONECANPAY` was already incompatible.  Indeed, the spec says that it is.  Interestingly, the code we got from Flowee in BCHN for this didn't actually try to enforce this directly -- just the validation would fail for this sighash type.  

So, consequently, the BCHN RPC that returns a dsproof score pretends like these `ANYONECANPAY` txns are dsproof-able.. then in reality they are not!  Oops!
