### ISSUE TITLE
`SIGHASH_UTXOS` wants to use sighash flag `0x20`, however this has an interesting history, not sure what to make of it.

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#56]
Please see this note: https://github.com/mit-dci/cash-disclosure/blob/master/bitcoin-cash-disclosure-04252018.txt

Are any current transactions on-chain using `0x20`?

**Comment by cculianu** [comment]
It appears this was just an old bug in the consensus code that's since been plugged.  Nothing to do with `0x20` itself as being evil.  Just was a bug in ABC at one point that it allowed this flag even though it should not have.  Closing.

**Comment by bitjson** [comment]
Thanks for opening the issue and looking into it!
