### ISSUE TITLE
Specify that `SIGHASH_UTXOS` must also have `SIGHASH_FORKID` otherwise sigHashType is invalid

### ISSUE THREAD

**Issue by cculianu** [bitjson/cashtokens#57]
While this is implicit because of the fact that `SIGHASH_FORKID` is always required after August 2017, it would be nice to also see this in the specification as an explicitly stated thing.

This would avoid some implementations from e.g. forgetting to check that this flag must be active and somehow accepting "old" blocks that were invalid but that happened to use `0x20` -- this concern I have is imaginary really because we checkpoint in our nodes but -- just in case, it is worth mentioning in the spec.

**Comment by bitjson** [comment]
Sounds reasonable to me! I'll be sure to include that in the transaction test vectors too.
