### ISSUE TITLE
Why "Category"?

### ISSUE THREAD

**Issue by fpelliccioni** [bitjson/cashtokens#66]
https://github.com/bitjson/cashtokens/blob/54ea2d20e7576379a4f1783613c393ae3660ec68/readme.md#technical-summary

I think the term "category" is something confusing.
In the document it would seem that the terms "token" and "category" are used interchangeably.
It seems to me that the use of the term "token" is much more accepted by the community of smart contract developers.

**Comment by A60AB5450353F40E** [comment]
Andrew had chosen "group" because the ID groups a set of TXOs, puts them in a basket of sorts. Category is the same logic (utxos have a shared property, they all belong to the same category, encode the same tokens - those descending from the particular genesis TX), but more formally correct:

>Any [directed graph](https://en.wikipedia.org/wiki/Directed_graph) [generates](https://en.wikipedia.org/wiki/Generating_set) a small category: the objects are the [vertices](https://en.wikipedia.org/wiki/Vertex_(graph_theory)) of the graph, and the morphisms are the paths in the graph (augmented with [loops](https://en.wikipedia.org/wiki/Loop_(graph_theory)) as needed) where composition of morphisms is concatenation of paths. Such a category is called the [free category](https://en.wikipedia.org/wiki/Free_category) generated by the graph.

Some past discussion here: https://github.com/bitjson/cashtokens/issues/8

**Comment by bitjson** [comment]
Thanks for the issue @fpelliccioni!

If I understand the question:

We have a term for `category` to make it easier to identify when someone is talking about:
1. a specific instance of a token (e.g. a single NFT, or a fungible token amount of `1`), or
2. a specific "category" of tokens, e.g. "FernandoCoins".

So you might create the "FernandoCoins" `category` with an amount of fungible tokens + some NFTs. Any one of those individual tokens you created is also a `token`, but it's useful to have a term to describe the larger set of tokens that were created.

From a wallet's perspective, every token has a `category` property, and fungible token amounts from the same category make up the wallets token balance for that category. (NFTs can't be summed, so wallets also need to be able to indicate that the user owns a number of NFTs and somehow allow them to be listed individually.)

Does that answer the question?

And as @A60AB5450353F40E mentioned, [other terms were considered here](https://github.com/bitjson/cashtokens/issues/8): `category, genesis, origin, breed, species, color, classification, class, type, kind, collection, and group`

**Comment by A60AB5450353F40E** [comment]
The "different things" being grouped are BCH UTXOs. EVMs don't have UTXOs so there's nothing to "group" I guess. Probably everyone will call them tokens and label the ID as tokenID because we expect the primitives to be used mostly for tokens. More formally, some tokens you may hold will be a subset of a category of BCH UTXOs :) This "grouping" is more fundamental than tokens, it solves the unforgeability & inductive proof problem - how do you know where your UTXO came from? How do you know it respected rules of some contract since contract inception? If it belongs to a category, you can be assured it came from the category's genesis TX, and if the genesis TX had the right contract then by induction you can be assured the whole chain respected the contract without having to look at the chain. It doesn't have to be a token, when dealing with contracts the unforgeability property gets more abstract.

My Group CHIP attempted to shine some light on this, too:

> Contracts now have full access to the whole transaction they're being spent in and can make decisions based on content and satoshi value of any other input and output in the same transaction.
> This alone enables much versatility in designing application, and one important class of application is the covenant.
> Covenant is a class of contracts that requires its own code to be passed on to newly created outputs, on top of which further requirements may be placed.
> One simple example of a covenant would be a [contract](https://read.cash/@Telesfor/mecenas-recurring-payment-smart-contract-plugin-3e6487be) that allows only a fixed amount of BCH to be taken out at fixed time intervals, that has been made much simpler and smaller [(900 bytes per transaction down to 243 bytes)](https://t.me/bch_compilers/5090) by introduction of introspection opcodes.
> Covenant contracts create chains of transactions that each link-up and lead back to the first one, the contract's instance genesis transaction.
> The covenant's self-replication code ensures that the chain can't be broken by future spenders - if they want to spend then they MUST extend the covenant's chain.
> Problem on Bitcoin Cash blockchain is, anyone can copy the contract code and create a new chain.
> Someone who inspects just the last transaction has no way of knowing from which starting point the tip of the chain is coming - he must follow the whole chain back to the contract's instance genesis transaction.
> This is easy to verify by external observers: they query the blockchain for past transaction until they reach the tip.
> However, what if we wanted to create some other contract that required a spend from a particular chain?
> What if we wanted to create a non-fungible token (NFT) contract w[here](https://blog.bitjson.com/pmv3-build-decentralized-applications-on-bitcoin-cash/) we'd want to be sure it's the real one without having to look up the whole history?
> With current Bitcoin Cash blockchain features - such contracts are impossible to construct because a covenant contract can't prove its own genesis using a fixed size proof.
> The problem has been independently discovered by many individuals interested in Bitcoin Cash developments, and is well illuminated here.
> Later, an [example demonstrated](https://old.reddit.com/r/btc/comments/rasju1/limits_of_introspection_and_why_we_need_pmv3group/) how even with the latest upgrade, the same fundamental problem prevents such contracts from being made.
> Cornerstone feature of this proposal is solving the proof-of-genesis problem by enabling unforgeable contracts, contracts that carry a compact fixed-size proof of their own genesis transaction.
> To actually make those contracts practical and useful in building decentralized applications, two hard-coded unforgeable contracts are proposed on top of unforgeable contracts, that will enable native token primitives: fungible token (FT) super-contracts and non-fungible token (NFT) super-contracts.
> Those will allow decentralized applications to be built simply and efficiently, by using Script VM to combine them in a way  that allows complex structures to exist on Bitcoin Cash blockchain, and all without impacting scaling properties of the network.

> Bitcoin Cash already is programmable cash, where every unit of cash carries a program (a "smart contract") that determines how it may be spent.
> Most common such program is known as an "address", which simply requires a signature in order to spend the cash unit.
> We will first introduce the concept of unforgeable contracts, that enables units of BCH to be marked with an unique identifier which will serve as proof that some BCH amount came from a particular contract instance.
> Bitcoin Cash units that inherit from the same unforgeable contract instance can be thought of as forming an exclusive category of cash units, where membership is controlled exclusively by current members, thus we title this proposal unforgeable categories (of BCH outputs).
> We will then use that as a fundamental feature on top of which to build native token primitives through introducing two essential "super-contracts", non-fungible token (NFT) and fungible token (FT) contracts enforced by native consensus code, that can be seamlessly used by Bitcoin Cash Script contracts to create efficient token systems tailored to their purpose.
> [Transaction format](https://github.com/bitjson/cashtokens/issues/66#transaction-format) will be extended to allow [transaction outputs](https://github.com/bitjson/cashtokens/issues/66#categorized-output-format) to optionally carry a category identifier using the non-breaking [PreFiX](https://gitlab.com/bitcoin-cash-node/announcements/-/blob/master/2021-12-23_evaluate_viability_of_transaction_format_or_id_change_EN.md#an-alternative-to-breaking-change) method.
> We will refer to all transaction outputs (TXOs) having a common identifier as a category (of BCH outputs), and individual such outputs as categorized outputs.
> New outputs will be allowed into an existing category only by spending an unspent transaction output (UTXO) of the same category in the same transaction, [allowing only existing members to introduce new members](https://github.com/bitjson/cashtokens/issues/66#category-membership).
> Transaction [input format](https://github.com/bitjson/cashtokens/issues/66#category-genesis-input-format) will be extended similarly to outputs, so inputs may be spent as [category genesis](https://github.com/bitjson/cashtokens/issues/66#category-genesis) inputs.
> Such inputs will be the only way to allow creation of outputs with a newly generated category identifier.
> The identifier will be deterministically generated based on the input's unique data, therefore every category genesis transaction will be unique.
> By induction, every category will be exclusive to descendants of the category's genesis input, therefore category membership will be unforgeable.
> Additionally, the format will allow categorized outputs to encode token state using a fixed-size [nft type](https://github.com/bitjson/cashtokens/issues/66#nft-type) field, a fixed-size fungible token (FT) amount field, and a variable-length non-fungible token (NFT) message field.
> Native tokens will be enabled by two [native token "super-contracts"](https://github.com/bitjson/cashtokens/issues/66#native-token-super-contracts), kind of contract directly enforced by consensus code, that will place immutable rules on how token state may evolve across any single transaction involving categorized outputs.
> The enforcement will be transaction-local, and immutable category properties will be globally guaranteed by induction:
> 
> - unforgeability of the category identifier,
> - non-fungible tokens cardinality (number of outputs),
> - non-fungible tokens message authenticity,
> - fungible tokens accounting equation.
> 
> [Introspection opcodes] will be extended to access categorized output fields and input's category genesis fields.
> [Transaction signing](https://github.com/bitjson/cashtokens/issues/66#transaction-signing) will be updated with a new signature hash type which will be mandatory for signing transactions involving categorized outputs.
> [Network rules](https://github.com/bitjson/cashtokens/issues/66#network-rules) will be updated to allow transactions with categorized output templates to be relayed while the network message format will remain the same.
> [Wallet address format](https://github.com/bitjson/cashtokens/issues/66#address-format) update will be discussed and shown to be unnecessary.

**Comment by bitjson** [comment]
I think this is answered, but feel free to re-open if there's more to discuss here. (Also happy to hop on a call if a higher-bandwidth discussion would help!)
