### ISSUE TITLE
Rationale of the "amount" valid interval

### ISSUE THREAD

**Issue by fpelliccioni** [bitjson/cashtokens#67]
https://github.com/bitjson/cashtokens/blob/54ea2d20e7576379a4f1783613c393ae3660ec68/readme.md#transaction-output-data-model

Nit: The range of valid integers for "amount" should be correctly specified.
I understand that it is `[1, 9223372036854775807]` (using square brackets as is common to define closed intervals).

Perhaps the most important is:
- Why `0` (zero) is not a valid `amount`?
- Why is `9223372036854775807` the largest `amount` allowed?

**Comment by A60AB5450353F40E** [comment]
- Why 0 (zero) is not a valid amount?

Because then the return value of `OP_*TOKENAMOUNT` would be ambiguous. If it would return 0 would it mean the output encodes a NFT with no FT, or it encodes an FT of 0 amount, or it encodes a NFT+FT amount 0?

- Why is `9223372036854775807` the largest amount allowed?

To align with Script VM and not have weird smart contract edge cases. It is the biggest amount that can be manipulated as number by Script VM.

**Comment by bitjson** [comment]
Thanks for the issue @fpelliccioni, and thanks answering @A60AB5450353F40E!

To clarify, you **can** have a token prefix with an `amount` of `0` if that token prefix is also encoding an NFT. But **token prefixes that encode no tokens at all** are invalid. In general, we don't want the protocol support 2 different ways of encoding the same thing, and an "empty" token prefix can also be expressed by simply removing the prefix. (It's not necessarily a malleability vector, but it complicates implementations and creates more room for bugs and unexpected behavior.)

I'll add more specifically (there was [some discussion on Bitcoin Cash Research](https://bitcoincashresearch.org/t/chip-2022-02-cashtokens-token-primitives-for-bitcoin-cash/725/)): allowing amounts of `0` (without an NFT) would be somewhat ambiguous – it could be considered technically correct to specify an output with amount `0` for a token category that doesn't appear in the inputs. If we instead made it a special case, where only transactions with the category appearing in the inputs could have `0` amount outputs, we'd need to decide if the special case applied to input NFTs. (User has NFTs of the category, can they create empty FT amount outputs?)

The primary reason to have such a special case would be to sort of replicate the function of OP_RETURN outputs, but limited to the set of token holders (either FT-only or FT+NFT holders, depending on what we would decide above). However, that same functionality is already easy and cheap for contracts to do using the token inspection operations, and indexing data pushed in those `0` amount statements wouldn't necessarily be easier than indexing data with token-less OP_RETURN outputs, where the indexer/client checks that the transaction included the particular token types/categories needed. So we'd be adding ~33 bytes to those UTXOs – and encouraging applications to use UTXO space inefficiently – for little gain.

And of course as @A60AB5450353F40E mentioned, the later optimizations for zero-length commitments make the argument even stronger for disallowing empty token prefixes. That rationale is here: [Support for Zero-Length Commitments](https://github.com/bitjson/cashtokens/blob/54ea2d20e7576379a4f1783613c393ae3660ec68/rationale.md#support-for-zero-length-commitments)

---

>> 9223372036854775807
>
> (Facepalm)
> Do not worry about it. I implemented a year ago and I forgot about that limit.

@fpelliccioni know this (he implemented that part of the May 2022 upgrade in BCHN 😄), but for anyone else finding this issue, note there's a rationale section for the fungible token limit here: [Limitation of Fungible Token Supply](https://github.com/bitjson/cashtokens/blob/54ea2d20e7576379a4f1783613c393ae3660ec68/rationale.md#limitation-of-fungible-token-supply)

**Comment by bitjson** [comment]
I think this is answered, but feel free to re-open if there's more to discuss here!
