### ISSUE TITLE
Confusion about "Capability"

### ISSUE THREAD

**Issue by fpelliccioni** [bitjson/cashtokens#73]
These two definitions seem to be contradictory:

> The capability of the NFT held in this output: none, mutable, or minting. This field is omitted if no NFT is present.

> The reserved supply of a fungible token category can be computed by retrieving all UTXOs which contain token prefixes matching the category ID,  removing provably-destroyed outputs (spent to OP_RETURN outputs), and summing the amounts held in prefixes which have either the minting or mutable capability.

**Comment by A60AB5450353F40E** [comment]
In the 2nd quoted paragraph, it talks about mixed-type UTXOs, where it encodes FT+NFT of the same category. So "summing the amounts held in prefixes which have either the minting or mutable capability" should be read as: summing FT amounts held in prefixes where the prefix also encodes an NFT of the minting or mutable capability.

It's an UTXO which has BCH+FT+NFT, and the NFT is used as a marker - and the NFT is what has the capability. The meaning of the mark is a matter of convention, and in that example it would mark an "official" supply.

**Comment by bitjson** [comment]
Thanks @A60AB5450353F40E! 

I think this is answered, but feel free to re-open if there's more to discuss here.
