### ISSUE TITLE
Encode of none capability

### ISSUE THREAD

**Issue by fpelliccioni** [bitjson/cashtokens#74]
- `mutable` `capability` is encoded as `0x01` 
- `minting` `capability` is encoded as `0x02` 

What about `none`? Is it `0x00`?

**Comment by A60AB5450353F40E** [comment]
Yes, it is serialized as `0x00` however note that OP_*CATEGORY treats it as `{}` so capability `none` will return a 32b stack item, it will not append the `0x00`.

**Comment by bitjson** [comment]
Thanks @A60AB5450353F40E!

I think this is answered, but feel free to re-open if there's more to discuss here.
