### ISSUE TITLE
Terminology: `Commitment`, `Category`

### ISSUE THREAD

**Issue by A60AB5450353F40E** [bitjson/cashtokens#8]
Disambiguate from cryptographic commitment which means hash of a message: https://en.wikipedia.org/wiki/Commitment_scheme#Bit-commitment_in_the_random_oracle_model

In this proposal, the NFT can carry an arbitrary user-set message, it doesn't have to be a hash of something although the covenant may require it to be.

**Comment by bitjson** [comment]
If anyone has other ideas on terminology, please share!

I'm going to close this issue for now, but please leave a comment if it should be reopened.

**Comment by A60AB5450353F40E** [comment]
>I don't think it conflicts.

Ugh... P2PKH and P2SH addresses are a commitment, TXID is a commitment, now also the nft message would be a commitment. Can we just call it what it is: nft message? (which may or may not be a hash, it may be used as a counter, too)

**Comment by A60AB5450353F40E** [comment]
I'm pondering  renaming the group chip to "unforgeable categories", while explaining the logic  behind the  "unforgeable groups" name I realized that in maths a "group"  is something that may not be adequate.

From math point of view, [category](https://en.wikipedia.org/wiki/Category_(mathematics)) is a better fit:

>Any [directed graph](https://en.wikipedia.org/wiki/Directed_graph) [generates](https://en.wikipedia.org/wiki/Generating_set) a small category: the objects are the [vertices](https://en.wikipedia.org/wiki/Vertex_(graph_theory)) of the graph, and the morphisms are the paths in the graph (augmented with [loops](https://en.wikipedia.org/wiki/Loop_(graph_theory)) as needed) where composition of morphisms is concatenation of paths. Such a category is called the [free category](https://en.wikipedia.org/wiki/Free_category) generated by the graph.

Also, [dictionary definition](https://dictionary.cambridge.org/dictionary/english/category):

>(in a [system](https://dictionary.cambridge.org/dictionary/english/system) for [dividing](https://dictionary.cambridge.org/dictionary/english/divide) things [according](https://dictionary.cambridge.org/dictionary/english/accord) to [appearance](https://dictionary.cambridge.org/dictionary/english/appearance), [quality](https://dictionary.cambridge.org/dictionary/english/quality), etc.) a [type](https://dictionary.cambridge.org/dictionary/english/type), or a [group](https://dictionary.cambridge.org/dictionary/english/group) of things having some [features](https://dictionary.cambridge.org/dictionary/english/feature) that are the same:
