### ISSUE TITLE
Verify my CASHTOKENS and NFT's ? 

### ISSUE THREAD

**Issue by kyleg2929** [bitjson/cashtokens#98]
i am now producing BCH CASHTOKENS as well as NFT's . i have been told that i do not need to verify them, but i thought that it was part of the process. can someone please explain what differencees it makes to verify the assets? also, where is the best place to have them verified.

**Comment by bitjson** [comment]
This repo is only for the CashTokens upgrade specification, but maybe these other resources will be useful: 
- https://cashtokens.org/docs/bcmr/chip
- https://otr.cash/
